### PR TITLE
Compressed all png files

### LINKED ISSUE #38: Binary too big
The resulting APK is too big. Probably because of dupe assets for compatibility. Fix fast.

### PR DESCRIPTION
**Pull request by akhillllldev**
This might fix #38

### CODE REVIEW

**Review by akhillllldev — COMMENTED** [review]
This might work. What do you think @2DSharp ?

**Comment by 2DSharp** [comment]
Can you generate a binary and check the size? Looks like an average of 30% decrease.

**Comment by akhillllldev** [comment]
> Can you generate a binary and check the size? Looks like an average of 30% decrease.

45 MB

**Comment by 2DSharp** [comment]
Looks good for now

**Review by 2DSharp — APPROVED** [review]
Seems like a much better improvement, merging

**Pull request merged**
